version: '2'

volumes:
  settings:                          # Only required if using PERSISTENT flag (see below)
  avahi-socket-dir: {}

services:
  avahi:
    image: flungo/avahi
    network_mode: host
    volumes:
      - "avahi-socket-dir:/var/run/avahi-daemon"
    environment:
      # Separation of responsibilities, this daemon is query-only. The hosts daemon publishes:
      PUBLISH_DISABLE_PUBLISHING: "yes"

  browser:
    build: .
    privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
    ports:
        - '5011' # management API (optional)
        - '35173' # Chromium debugging port (optional)
    volumes:
      - 'settings:/data' # Only required if using PERSISTENT flag (see below)
      - "avahi-socket-dir:/var/run/avahi-daemon"
    network_mode: host
    
  webserver:
    build: ./webserver
    ports:
      - "80:80"
